#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "filegator"
name = "FileGator"
description.en = "Multi-User File Manager"
description.fr = "Gestionnaire de fichiers multi-utilisateurs"

version = "7.14.3~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://filegator.io/"
demo = "https://demo.filegator.io/"
admindoc = "https://docs.filegator.io/"
code = "https://github.com/filegator/filegator"
fund = "https://www.patreon.com/alcalbg"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "130M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/filegator"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["english", "french", "german", "italian", "spanish"]
    default = "french"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/filegator/static/raw/master/builds/filegator_v7.14.3.zip"
    sha256 = "65b6d5d7893bb8daad524b97ca84405a824f71cdcdae1b4e3ecb8e78f8012f17"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.5-zip, php8.5-mbstring, php8.5-dom, php8.5-xml"
